set(CMAKE_SYSTEM_NAME Windows)

set(CMAKE_C_COMPILER   i686-w64-mingw32-gcc)
set(CMAKE_CXX_COMPILER i686-w64-mingw32-g++)

set(CMAKE_FIND_ROOT_PATH  /mingw/i686-w64-mingw32)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)

set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

if(TARGET_WINXP)
    add_definitions(-D_WIN32_WINNT=0x0501)

    set(HAVE_D3D11_H 0 CACHE INTERNAL "")
    set(HAVE_D3D12_H 0 CACHE INTERNAL "")
    set(HAVE_SHELLSCALINGAPI_H 0 CACHE INTERNAL "")
endif()
